//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gastronomy.Dtos.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Gastronomy.Dtos.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ta nazwa jest już zajęta..
        /// </summary>
        public static string DishCategoryNameTakenErrorMessage {
            get {
                return ResourceManager.GetString("DishCategoryNameTakenErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ta nazwa jest już zajęta..
        /// </summary>
        public static string DishNameTakenErrorMessage {
            get {
                return ResourceManager.GetString("DishNameTakenErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nazwa nie może być pusta..
        /// </summary>
        public static string EmptyDishNameErrorMessage {
            get {
                return ResourceManager.GetString("EmptyDishNameErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Poniważ została wybrana nowa kategoria, nie można jednocześnie ustawić istniejącej..
        /// </summary>
        public static string ExistingDishCategoryMustBeNullWhenNewSelectedErrorMessage {
            get {
                return ResourceManager.GetString("ExistingDishCategoryMustBeNullWhenNewSelectedErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nazwa nowej kategorii jest wymagana..
        /// </summary>
        public static string NewCategoryNameEmptyErrorMessage {
            get {
                return ResourceManager.GetString("NewCategoryNameEmptyErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ponieważ została wybrana istniejąca kategoria, nie można jednocześnie dodać nowej..
        /// </summary>
        public static string NewDishCategoryMustBeNullWhenExistingSelectedErrorMessage {
            get {
                return ResourceManager.GetString("NewDishCategoryMustBeNullWhenExistingSelectedErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kategoria jest wymagana.
        /// </summary>
        public static string NullExistingCategoryErrorMessage {
            get {
                return ResourceManager.GetString("NullExistingCategoryErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cena nie może być mniejsza niż {0}..
        /// </summary>
        public static string PriceLessOrEqualToErrorMessage {
            get {
                return ResourceManager.GetString("PriceLessOrEqualToErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ta kategoria nie istnieje.
        /// </summary>
        public static string ThisDishCategoryDoesNotExistErrorMessage {
            get {
                return ResourceManager.GetString("ThisDishCategoryDoesNotExistErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nazwa nie może przekraczać {0} znaków..
        /// </summary>
        public static string TooLongDishCategoryNameErrorMessage {
            get {
                return ResourceManager.GetString("TooLongDishCategoryNameErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nazwa nie może przekraczać {0} znaków..
        /// </summary>
        public static string TooLongDishNameErrorMessage {
            get {
                return ResourceManager.GetString("TooLongDishNameErrorMessage", resourceCulture);
            }
        }
    }
}
